name: Implementing workflow variables

on:
  workflow_dispatch

# Workflow scope variables
env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    # Job scoped variables
    env:
      Greeting: Hello
    steps:
      - name: "Say Hi visitor, this is created on Monday"
        run: echo "$Greeting $First_Name is using #cloud!"
        # Step scoped variable
        env:
          First_Name: Vishal
